<template>
  <div id="pageFour">
    PAGE PAGEFOUR PAGEFOUR PAGEFOUR PAGEFOUR PAGEFOUR PAGEFOUR PAGEFOUR PAGEFOUR PAGEFOUR PAGEFOUR ONE <br>
    PAGE PAGEFOUR PAGEFOUR PAGEFOUR PAGEFOUR PAGEFOUR PAGEFOUR PAGEFOUR PAGEFOUR PAGEFOUR PAGEFOUR ONE <br>
    PAGE PAGEFOUR PAGEFOUR PAGEFOUR PAGEFOUR PAGEFOUR PAGEFOUR PAGEFOUR PAGEFOUR PAGEFOUR PAGEFOUR ONE <br>

</div>
</template>

<script>
export default {
  name: 'pageFour',
}
</script>
<!-- styling for the component -->
<style>
#pageFour {

}
</style>
