<template>
  <div id="pageFive">
    PAGE PAGEFIVE PAGEFIVE PAGEFIVE PAGEFIVE PAGEFIVE PAGEFIVE PAGEFIVE PAGEFIVE PAGEFIVE PAGEFIVE ONE <br>
    PAGE PAGEFIVE PAGEFIVE PAGEFIVE PAGEFIVE PAGEFIVE PAGEFIVE PAGEFIVE PAGEFIVE PAGEFIVE PAGEFIVE ONE <br>
    PAGE PAGEFIVE PAGEFIVE PAGEFIVE PAGEFIVE PAGEFIVE PAGEFIVE PAGEFIVE PAGEFIVE PAGEFIVE PAGEFIVE ONE <br>
  </div>
</template>

<script>
export default {
  name: 'PageFiveViews'
}
</script>
<!-- styling for the component -->
<style>
#pageFive {

  margin-top: 60px;
}
</style>
